/ur5bh:
  shoulder_pan_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: shoulder_pan_joint
    gain: 1000.0

  shoulder_lift_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: shoulder_lift_joint
    gain: 1000.0
    
  elbow_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: elbow_joint
    gain: 1000.0
    
  wrist_1_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: wrist_1_joint
    gain: 1000.0

  wrist_2_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: wrist_2_joint
    gain: 1000.0

  wrist_3_joint_controller:
    type: my_controller_ns/MyControllerClass
    joint: wrist_3_joint
    gain: 1000.0

# ur5bh:
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50  

#   bh_j11_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j11_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}
    
#   bh_j12_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j12_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

#   bh_j13_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j13_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

#     bh_j21_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j21_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}
    
#   bh_j22_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j22_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

#   bh_j23_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j23_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}


#   bh_j31_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j31_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}
    
#   bh_j32_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j32_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

#   bh_j33_joint_controller:
#     type: effort_controllers/JointPositionController
#     joint: bh_j33_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}